---
version: "3"
services:
  hubot:
    build: .
    env_file:
      - common.env
      - secrets.env
    expose:
      - 8080
    depends_on:
      - redis
    volumes: 
      - ".:/app"
  redis:
    image: "redis:alpine"
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - "./brain:/data"
